['GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch']

In [1]:
import random

from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

import graphviz
from tqdm import tqdm
from sklearn.metrics import f1_score

from matplotlib import pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.tree import export_graphviz

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures
from sklearn.datasets import make_circles
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import mean_absolute_percentage_error as MAPE

In [2]:
train_df = pd.read_csv('train.csv')
train_df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
my_features_df = train_df[['GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch']]
my_features_df

,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch
0,2,548,TA,TA,Y,0,61,0,0,0
1,2,460,TA,TA,Y,298,0,0,0,0
2,2,608,TA,TA,Y,0,42,0,0,0
3,3,642,TA,TA,Y,0,35,272,0,0
4,3,836,TA,TA,Y,192,84,0,0,0
...,...,...,...,...,...,...,...,...,...,...
1455,2,460,TA,TA,Y,0,40,0,0,0
1456,2,500,TA,TA,Y,349,0,0,0,0
1457,1,252,TA,TA,Y,0,60,0,0,0
1458,1,240,TA,TA,Y,366,0,112,0,0
1459,1,276,TA,TA,Y,736,68,0,0,0

- GarageCars: Size of garage in car capacity --------------- Размер гаража по вместимости автомобиля
- GarageArea: Size of garage in square feet ---------------- Размер гаража в квадратных футах
- GarageQual: Garage quality ------------------------------- Гаражное качество
    - Ex	Excellent           5
    - Gd	Good                4
    - TA	Typical/Average     3
    - Fa	Fair                2
    - Po	Poor                1
    - NA	No Garage           0
- GarageCond: Garage condition ----------------------------- Состояние гаража
    - Ex	Excellent           5
    - Gd	Good                4
    - TA	Typical/Average     3
    - Fa	Fair                2
    - Po	Poor                1
    - NA	No Garage           0 
- PavedDrive: Paved driveway ------------------------------- Асфальтированная подъездная дорога
    - Y	Paved                   3
    - P	Partial Pavement        2
    - N	Dirt/Gravel             1
- WoodDeckSF: Wood deck area in square feet ---------------- Площадь деревянного настила в квадратных футах (вероятно, речь о террасе или о террасах??)
- OpenPorchSF: Open porch area in square feet -------------- Площадь открытой веранды в квадратных футах
- EnclosedPorch: Enclosed porch area in square feet -------- Закрытая веранда в квадратных футах
- 3SsnPorch: Three season porch area in square feet -------- Площадь веранды на три сезона в квадратных футах
- ScreenPorch: Screen porch area in square feet ------------ Площадь веранды в квадратных футах

In [40]:
print(my_features_df['GarageCars'].unique())
print(my_features_df['GarageCars'].value_counts())
print(my_features_df['GarageCars'].isna().sum())

[2 3 1 0 4]
GarageCars
2    824
1    369
3    181
0     81
4      5
Name: count, dtype: int64
0

In [38]:
print(my_features_df['GarageArea'].unique())
print(my_features_df['GarageArea'].value_counts())
print(my_features_df['GarageArea'].isna().sum())

[ 548  460  608  642  836  480  636  484  468  205  384  736  352  840
  576  516  294  853  280  534  572  270  890  772  319  240  250  271
  447  556  691  672  498  246    0  440  308  504  300  670  826  386
  388  528  894  565  641  288  645  852  558  220  667  360  427  490
  379  297  283  509  405  758  461  400  462  420  432  506  684  472
  366  476  410  740  648  273  546  325  792  450  180  430  594  390
  540  264  530  435  453  750  487  624  471  318  766  660  470  720
  577  380  434  866  495  564  312  625  680  678  726  532  216  303
  789  511  616  521  451 1166  252  497  682  666  786  795  856  473
  398  500  349  454  644  299  210  431  438  675  968  721  336  810
  494  457  818  463  604  389  538  520  309  429  673  884  868  492
  413  924 1053  439  671  338  573  732  505  575  626  898  529  685
  281  539  418  588  282  375  683  843  552  870  888  746  708  513
 1025  656  872  292  441  189  880  676  301  474  706  617  445  200
  592  566  514  296  244  610  834  639  501  846  560  596  600  373
  947  350  396  864  304  784  696  569  628  550  493  578  198  422
  228  526  525  908  499  508  694  874  164  402  515  286  603  900
  583  889  858  502  392  403  527  765  367  426  615  871  570  406
  590  612  650 1390  275  452  842  816  621  544  486  230  261  531
  393  774  749  364  627  260  256  478  442  562  512  839  330  711
 1134  416  779  702  567  832  326  551  606  739  408  475  704  983
  768  632  541  320  800  831  554  878  752  614  481  496  423  841
  895  412  865  630  605  602  618  444  397  455  409  820 1020  598
  857  595  433  776 1220  458  613  456  436  812  686  611  425  343
  479  619  902  574  523  414  738  354  483  327  756  690  284  833
  601  533  522  788  555  689  796  808  510  255  424  305  368  824
  328  160  437  665  290  912  905  542  716  586  467  582 1248 1043
  254  712  719  862  928  782  466  714 1052  225  234  324  306  830
  807  358  186  693  482  813  995  757 1356  459  701  322  315  668
  404  543  954  850  477  276  518 1014  753 1418  213  844  860  748
  248  287  825  647  342  770  663  377  804  936  722  208  662  754
  622  620  370 1069  372  923  192]
GarageArea
0      81
440    49
576    47
240    38
484    34
       ..
320     1
594     1
831     1
878     1
192     1
Name: count, Length: 441, dtype: int64
0

In [36]:
print(my_features_df['GarageQual'].unique())
print(my_features_df['GarageQual'].value_counts())
print(my_features_df['GarageQual'].isna().sum())

['TA' 'Fa' 'Gd' nan 'Ex' 'Po']
GarageQual
TA    1311
Fa      48
Gd      14
Ex       3
Po       3
Name: count, dtype: int64
81

In [35]:
print(my_features_df['GarageCond'].unique())
print(my_features_df['GarageCond'].value_counts())
print(my_features_df['GarageCond'].isna().sum())

['TA' 'Fa' nan 'Gd' 'Po' 'Ex']
GarageCond
TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: count, dtype: int64
81

In [41]:
print(my_features_df['PavedDrive'].unique())
print(my_features_df['PavedDrive'].value_counts())
print(my_features_df['PavedDrive'].isna().sum())

['Y' 'N' 'P']
PavedDrive
Y    1340
N      90
P      30
Name: count, dtype: int64
0

In [44]:
print(my_features_df['WoodDeckSF'].describe())
print(my_features_df['WoodDeckSF'].value_counts())
print(my_features_df['WoodDeckSF'].isna().sum())

count    1460.000000
mean       94.244521
std       125.338794
min         0.000000
25%         0.000000
50%         0.000000
75%       168.000000
max       857.000000
Name: WoodDeckSF, dtype: float64
WoodDeckSF
0      761
192     38
100     36
144     33
120     31
      ...
326      1
179      1
103      1
176      1
736      1
Name: count, Length: 274, dtype: int64
0

In [45]:
print(my_features_df['OpenPorchSF'].describe())
print(my_features_df['OpenPorchSF'].value_counts())
print(my_features_df['OpenPorchSF'].isna().sum())

count    1460.000000
mean       46.660274
std        66.256028
min         0.000000
25%         0.000000
50%        25.000000
75%        68.000000
max       547.000000
Name: OpenPorchSF, dtype: float64
OpenPorchSF
0      656
36      29
48      22
20      21
40      19
      ...
11       1
523      1
125      1
137      1
236      1
Name: count, Length: 202, dtype: int64
0

In [48]:
print(my_features_df['EnclosedPorch'].describe())
print(my_features_df['EnclosedPorch'].value_counts())
print(my_features_df['EnclosedPorch'].isna().sum())

count    1460.000000
mean       21.954110
std        61.119149
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       552.000000
Name: EnclosedPorch, dtype: float64
EnclosedPorch
0      1252
112      15
96        6
192       5
144       5
       ...
54        1
136       1
148       1
140       1
99        1
Name: count, Length: 120, dtype: int64
0

In [47]:
print(my_features_df['3SsnPorch'].describe())
print(my_features_df['3SsnPorch'].value_counts())
print(my_features_df['3SsnPorch'].isna().sum())

count    1460.000000
mean        3.409589
std        29.317331
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       508.000000
Name: 3SsnPorch, dtype: float64
3SsnPorch
0      1436
168       3
144       2
180       2
216       2
290       1
153       1
96        1
23        1
162       1
182       1
196       1
320       1
245       1
238       1
508       1
140       1
130       1
407       1
304       1
Name: count, dtype: int64
0

In [50]:
print(my_features_df['ScreenPorch'].describe())
print(my_features_df['ScreenPorch'].value_counts())
print(my_features_df['ScreenPorch'].isna().sum())

count    1460.000000
mean       15.060959
std        55.757415
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max       480.000000
Name: ScreenPorch, dtype: float64
ScreenPorch
0      1344
192       6
120       5
224       5
189       4
       ...
291       1
260       1
385       1
156       1
40        1
Name: count, Length: 76, dtype: int64
0

In [16]:
my_features_df[['GarageQual', 'GarageCond']]

     GarageQual GarageCond
0            TA         TA
1            TA         TA
2            TA         TA
3            TA         TA
4            TA         TA
...         ...        ...
1455         TA         TA
1456         TA         TA
1457         TA         TA
1458         TA         TA
1459         TA         TA

[1460 rows x 2 columns]

In [30]:
# Создание нового столбца с условием
my_features_df['MergedColumn'] = my_features_df.apply(lambda row: row['GarageQual'] if row['GarageQual'] == row['GarageCond'] else f"{row['GarageQual']}_{row['GarageCond']}", axis=1)

# Вывод результата
my_features_df['MergedColumn'].unique()

C:\Users\User\AppData\Local\Temp\ipykernel_4244\2107925641.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  my_features_df['MergedColumn'] = my_features_df.apply(lambda row: row['GarageQual'] if row['GarageQual'] == row['GarageCond'] else f"{row['GarageQual']}_{row['GarageCond']}", axis=1)

array(['TA', 'Fa_TA', 'Gd_TA', 'TA_Fa', 'nan_nan', 'TA_Gd', 'Fa', 'Ex_TA',
       'Po', 'Ex', 'Fa_Po', 'Gd'], dtype=object)

Из моих 10 колонок 3 я вляются текстовыми, однако они легко кодируются в числовые, причём есть возможность отранжировать значения, ибо они обозначают качество или состояние гаража или подъездной дороги. Также в колонках про гараж GarageQual и GarageCond имеются значения nan, которые показывают, что гаража нет. Они связаны между собой по этому значению, а также у них одинаковй массив возможных значений.
7 колонок представляют собой числовые значения, которые являются целыми. Таким образом, нет необходимости их кодировать. Но можно нормализовать для задач, связанных с регрессиями. Для бустингов вряд ли это будет полезным, однако и вряд ли навредит. Получается, что три колонки мы точно кодируем, а две гаражные можно преобразовать в одну по принципу: nan = 0 , Ex = 5, остальные между ними соответсвующие целым числам. Cоединение делаем посредством среднего арифметического. В столбце про подъездную дорогу можно кодировать от 1 до 3, т.к. во всех строках есть какое-то (не nan) значение. 

Колонка 3SsnPorch имеет разбежку от 0 до 508, однако среднее значение всего 3 с мелочью при 1460 строках данных. То есть почти все строки - нули. Ее значимость под вопросом

Такая же история и с колонками EnclosedPorch и ScreenPorch. В обоих столбцах очень много нулей.

Чуть получше ситуация с OpenPorch. Но тоже близко к нулю. Точно не уверен, но есть мысль, что все эти порчи можно втупую сложить в один столбец "Common square of porches". тогда может оказаться, что их значение будет получше, ибо очень много колонок про веранды, а значения еле выше нуля.

Схожими свойствами обладает и WoodDeckSF. Очень много нулей, но ее нелогично соединять с чем-то типа веранд. Таким образом, этот столбец я выкинул бы первым, если задаться целью сократить количество столбцов.

Из всех столбцов самые полезные GarageCars и GarageArea. Во всех есть не nan значения, которые вполне понятным образом влияют на датасет. Полагаю, что работать необходимо именно с ними, тремя перекодированными столбцами и суммой порчей. это сократит количество столбцов до 6.